-- =============================================================================
-- Dienstplaner Import-Pipeline
-- PDF-Altdienstpläne (Analyse/Trainingsdaten) + Excel-Verfügbarkeiten
-- Führe dieses Script in deiner Supabase-Datenbank aus.
-- =============================================================================

create table if not exists dienstplan_imports (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('schedule_pdf', 'availability_xlsx')),
  file_name text not null,
  storage_path text,
  status text not null default 'parsed'
    check (status in ('parsed', 'confirmed', 'discarded', 'error')),
  period_start date,
  period_end date,
  parsed_rows jsonb not null default '[]'::jsonb,
  parse_notes text,
  error_message text,
  row_count integer not null default 0,
  confirmed_count integer,
  created_by text,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz
);
create index if not exists idx_dienstplan_imports_kind_created
  on dienstplan_imports(kind, created_at desc);

create table if not exists dienstplan_history_shifts (
  id bigint generated by default as identity primary key,
  import_id bigint references dienstplan_imports(id) on delete set null,
  shift_date date not null,
  employee_name text not null,
  employee_id bigint references dienstplan_employees(id) on delete set null,
  position text,
  start_time time,
  end_time time,
  source_note text,
  created_at timestamptz not null default now(),
  -- NULLS NOT DISTINCT: Schichten ohne erfasste Uhrzeit sollen sich beim
  -- erneuten Import trotzdem deduplizieren (PostgreSQL 15+).
  unique nulls not distinct (shift_date, employee_name, start_time, end_time)
);
create index if not exists idx_dienstplan_history_shifts_date
  on dienstplan_history_shifts(shift_date);
create index if not exists idx_dienstplan_history_shifts_employee
  on dienstplan_history_shifts(employee_id);
