-- db/schema.sql
create table if not exists roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  label text not null,
  description text,
  rank integer not null default 0,
  is_superadmin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists db_heartbeat (
  id bigint generated by default as identity primary key,
  pinged_at timestamptz not null default now()
);

create table if not exists dashboard_tiles (
  id text primary key,
  title text not null,
  body text not null,
  title_color text not null default '#f4f4f5',
  body_color text not null default '#a1a1aa',
  title_size integer not null default 22,
  body_size integer not null default 14,
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'title_color'
  ) then
    alter table dashboard_tiles add column title_color text not null default '#f4f4f5';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'body_color'
  ) then
    alter table dashboard_tiles add column body_color text not null default '#a1a1aa';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'title_size'
  ) then
    alter table dashboard_tiles add column title_size integer not null default 22;
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'body_size'
  ) then
    alter table dashboard_tiles add column body_size integer not null default 14;
  end if;
end $$;

-- Fallback: Ergänze fehlende ID-Spalte und Primärschlüssel, falls die Tabelle bereits ohne ID existiert
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'roles'
      and column_name = 'id'
  ) then
    alter table roles add column id bigint generated by default as identity;
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
     and tc.table_name = kcu.table_name
    where tc.table_schema = 'public'
      and tc.table_name = 'roles'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name = 'id'
  ) then
    alter table roles add primary key (id);
  end if;
end $$;

-- Fallback: db_heartbeat ID auf Identity-Default setzen, wenn noch kein Default vorhanden ist
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'db_heartbeat'
      and column_name = 'id'
      and column_default is null
  ) then
    alter table db_heartbeat alter column id add generated by default as identity;
  end if;
end $$;

-- Benutzer ↔ Rollen (mehrere Rollen pro Nutzer möglich)
create table if not exists user_roles (
  user_id text not null,
  role_id bigint not null references roles(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

-- Fein-granulare Berechtigungen pro Tool/Route (bool-basiert)
create table if not exists access_rules (
  route text not null,
  role text not null,
  allowed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (route, role)
);

-- Fallback: Ergänze fehlende Spalten, falls access_rules bereits ohne allowed existiert
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'access_rules'
      and column_name = 'allowed'
  ) then
    alter table access_rules add column allowed boolean not null default false;
  end if;
end $$;

-- Fein-granulare Berechtigungen pro Tool/Route
create table if not exists role_permissions (
  role_id bigint not null references roles(id) on delete cascade,
  route text not null,
  level smallint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (role_id, route)
);

-- Kinofilme (Filmdatenbank)
create table if not exists movies (
  id bigint generated by default as identity primary key,
  title text not null,
  runtime integer not null,
  pre_show integer not null default 25,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Kinovorstellungen (Spielplan)
create table if not exists shows (
  id bigint generated by default as identity primary key,
  hall integer not null,
  start_time timestamptz not null,
  movie_id bigint not null references movies(id) on delete cascade,
  version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Mitarbeitende
create table if not exists dienstplan_employees (
  id bigint generated by default as identity primary key,
  name text not null,
  position text,
  monthly_hours numeric(6,2) not null default 0,
  user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Pausenregeln
create table if not exists dienstplan_pause_rules (
  id bigint generated by default as identity primary key,
  min_minutes integer not null,
  pause_minutes integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Schichten
create table if not exists dienstplan_shifts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references dienstplan_employees(id) on delete cascade,
  shift_date date not null,
  start_time time,
  end_time time,
  raw_input text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, shift_date)
);

-- Basisrollen anlegen/aktualisieren (User + Admin)
insert into roles (name, label, rank, is_superadmin)
values
  ('user', 'User', 0, false),
  ('admin', 'Admin', 50, false)
on conflict (name) do update
set label = excluded.label,
    rank = excluded.rank,
    is_superadmin = excluded.is_superadmin,
    updated_at = now();

-- Standardberechtigungen befüllen (0=kein Zugriff, 1=Lesen, 2=Schreiben, 3=Admin)
with seed(role_name, route, level) as (
  values
    ('user', 'dashboard', 1),
    ('user', 'tools', 1),
    ('user', 'tools/files', 2),
    ('user', 'tools/journal', 2),
    ('user', 'tools/dispoplaner', 2),
    ('user', 'tools/dienstplaner', 2),
    ('user', 'tools/dienstplaner/settings', 2),
    ('admin', 'dashboard', 1),
    ('admin', 'admin', 1),
    ('admin', 'admin/users', 1),
    ('admin', 'admin/settings', 3),
    ('admin', 'settings', 1),
    ('admin', 'monitoring', 1),
    ('admin', 'tools', 2),
    ('admin', 'tools/files', 3),
    ('admin', 'tools/journal', 3),
    ('admin', 'tools/dispoplaner', 3),
    ('admin', 'tools/dienstplaner', 3),
    ('admin', 'tools/dienstplaner/settings', 3),
    ('admin', 'tools/storage', 2),
    ('admin', 'tools/system', 2),
    ('admin', 'activity', 1)
)
insert into role_permissions (role_id, route, level)
select r.id, seed.route, seed.level
from seed
join roles r on r.name = seed.role_name
on conflict (role_id, route) do update
set level = excluded.level,
    updated_at = now();

insert into access_rules (route, role, allowed)
select seed.route, seed.role_name, (seed.level > 0) as allowed
from seed
on conflict (route, role) do update
set allowed = excluded.allowed,
    updated_at = now();

create or replace function public.get_public_tables()
returns table (table_name text)
language sql
security definer
set search_path = public
as $$
  select table_name
  from information_schema.tables
  where table_schema = 'public'
    and table_type = 'BASE TABLE'
  order by table_name;
$$;
