-- /workspace/familiehake/db/schema.sql
create table if not exists roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  label text not null,
  description text,
  rank integer not null default 0,
  is_superadmin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists db_heartbeat (
  id bigint generated by default as identity primary key,
  pinged_at timestamptz not null default now()
);

create table if not exists dashboard_tiles (
  id text primary key,
  title text not null,
  body text not null,
  title_color text not null default '#f4f4f5',
  body_color text not null default '#a1a1aa',
  title_size integer not null default 22,
  body_size integer not null default 14,
  updated_at timestamptz not null default now()
);

create table if not exists theme_presets (
  id text primary key,
  label text not null,
  description text,
  css_vars jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists user_theme_preferences (
  user_id text primary key,
  preset_id text not null references theme_presets(id) on delete cascade,
  updated_at timestamptz not null default now()
);

insert into theme_presets (id, label, description, css_vars)
values
  (
    'dark',
    'Dunkel',
    'Aktuelles dunkles UI mit kräftigen Akzenten.',
    '{
      \"--background\": \"222 47% 10%\",
      \"--foreground\": \"210 40% 96%\",
      \"--card\": \"222 47% 12%\",
      \"--card-foreground\": \"210 40% 96%\",
      \"--popover\": \"222 47% 12%\",
      \"--popover-foreground\": \"210 40% 96%\",
      \"--primary\": \"189 94% 43%\",
      \"--primary-foreground\": \"210 40% 8%\",
      \"--secondary\": \"215 26% 22%\",
      \"--secondary-foreground\": \"210 40% 96%\",
      \"--muted\": \"218 30% 18%\",
      \"--muted-foreground\": \"214 20% 70%\",
      \"--accent\": \"199 89% 38%\",
      \"--accent-foreground\": \"210 40% 8%\",
      \"--destructive\": \"0 84% 63%\",
      \"--destructive-foreground\": \"210 40% 98%\",
      \"--border\": \"215 25% 25%\",
      \"--input\": \"215 25% 25%\",
      \"--ring\": \"199 89% 38%\",
      \"--chart-1\": \"199 89% 48%\",
      \"--chart-2\": \"170 72% 44%\",
      \"--chart-3\": \"31 89% 61%\",
      \"--chart-4\": \"145 63% 53%\",
      \"--chart-5\": \"25 86% 55%\",
      \"--accent-glow-1\": \"14 165 233\",
      \"--accent-glow-2\": \"56 189 248\",
      \"--accent-glow-3\": \"34 211 238\"
    }'::jsonb
  ),
  (
    'light',
    'Hell',
    'Helles Layout mit klaren Oberflächen und weichen Akzenten.',
    '{
      \"--background\": \"210 50% 98%\",
      \"--foreground\": \"222 40% 10%\",
      \"--card\": \"0 0% 100%\",
      \"--card-foreground\": \"222 40% 12%\",
      \"--popover\": \"210 40% 99%\",
      \"--popover-foreground\": \"222 40% 12%\",
      \"--primary\": \"196 88% 38%\",
      \"--primary-foreground\": \"210 40% 8%\",
      \"--secondary\": \"210 24% 90%\",
      \"--secondary-foreground\": \"222 40% 12%\",
      \"--muted\": \"210 24% 92%\",
      \"--muted-foreground\": \"215 20% 32%\",
      \"--accent\": \"186 88% 40%\",
      \"--accent-foreground\": \"210 40% 10%\",
      \"--destructive\": \"0 72% 50%\",
      \"--destructive-foreground\": \"0 0% 98%\",
      \"--border\": \"214 20% 80%\",
      \"--input\": \"214 20% 86%\",
      \"--ring\": \"196 88% 38%\",
      \"--chart-1\": \"199 89% 48%\",
      \"--chart-2\": \"170 72% 44%\",
      \"--chart-3\": \"31 89% 61%\",
      \"--chart-4\": \"145 63% 53%\",
      \"--chart-5\": \"25 86% 55%\",
      \"--accent-glow-1\": \"14 165 233\",
      \"--accent-glow-2\": \"37 99 235\",
      \"--accent-glow-3\": \"99 102 241\"
    }'::jsonb
  ),
  (
    'mid',
    'Mittelweg',
    'Zwischen hell und dunkel, mit ausgewogenen Kontrasten.',
    '{
      \"--background\": \"220 28% 16%\",
      \"--foreground\": \"210 40% 96%\",
      \"--card\": \"220 30% 18%\",
      \"--card-foreground\": \"210 40% 96%\",
      \"--popover\": \"220 30% 18%\",
      \"--popover-foreground\": \"210 40% 96%\",
      \"--primary\": \"191 95% 45%\",
      \"--primary-foreground\": \"210 40% 8%\",
      \"--secondary\": \"220 22% 24%\",
      \"--secondary-foreground\": \"210 40% 96%\",
      \"--muted\": \"220 22% 22%\",
      \"--muted-foreground\": \"214 20% 70%\",
      \"--accent\": \"199 85% 42%\",
      \"--accent-foreground\": \"210 40% 8%\",
      \"--destructive\": \"0 72% 55%\",
      \"--destructive-foreground\": \"210 40% 98%\",
      \"--border\": \"220 18% 30%\",
      \"--input\": \"220 18% 30%\",
      \"--ring\": \"199 85% 42%\",
      \"--chart-1\": \"199 89% 48%\",
      \"--chart-2\": \"170 72% 44%\",
      \"--chart-3\": \"31 89% 61%\",
      \"--chart-4\": \"145 63% 53%\",
      \"--chart-5\": \"25 86% 55%\",
      \"--accent-glow-1\": \"14 165 233\",
      \"--accent-glow-2\": \"56 189 248\",
      \"--accent-glow-3\": \"99 102 241\"
    }'::jsonb
  )
on conflict (id) do update
  set label = excluded.label,
      description = excluded.description,
      css_vars = excluded.css_vars,
      updated_at = now();

do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'title_color'
  ) then
    alter table dashboard_tiles add column title_color text not null default '#f4f4f5';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'body_color'
  ) then
    alter table dashboard_tiles add column body_color text not null default '#a1a1aa';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'title_size'
  ) then
    alter table dashboard_tiles add column title_size integer not null default 22;
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dashboard_tiles'
      and column_name = 'body_size'
  ) then
    alter table dashboard_tiles add column body_size integer not null default 14;
  end if;
end $$;

-- Fallback: Ergänze fehlende ID-Spalte und Primärschlüssel, falls die Tabelle bereits ohne ID existiert
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'roles'
      and column_name = 'id'
  ) then
    alter table roles add column id bigint generated by default as identity;
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
     and tc.table_name = kcu.table_name
    where tc.table_schema = 'public'
      and tc.table_name = 'roles'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name = 'id'
  ) then
    alter table roles add primary key (id);
  end if;
end $$;

-- Fallback: db_heartbeat ID auf Identity-Default setzen, wenn noch kein Default vorhanden ist
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'db_heartbeat'
      and column_name = 'id'
      and column_default is null
  ) then
    alter table db_heartbeat alter column id add generated by default as identity;
  end if;
end $$;

-- Benutzer ↔ Rollen (mehrere Rollen pro Nutzer möglich)
create table if not exists user_roles (
  user_id text not null,
  role_id bigint not null references roles(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

-- Fein-granulare Berechtigungen pro Tool/Route (bool-basiert)
create table if not exists access_rules (
  route text not null,
  role text not null,
  allowed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (route, role)
);

-- Fallback: Ergänze fehlende Spalten, falls access_rules bereits ohne allowed existiert
do $$
begin
  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'access_rules'
      and column_name = 'allowed'
  ) then
    alter table access_rules add column allowed boolean not null default false;
  end if;
end $$;

-- Fein-granulare Berechtigungen pro Tool/Route
create table if not exists role_permissions (
  role_id bigint not null references roles(id) on delete cascade,
  route text not null,
  level smallint not null default 0,
  updated_at timestamptz not null default now(),
  primary key (role_id, route)
);

-- Kinofilme (Filmdatenbank)
create table if not exists movies (
  id bigint generated by default as identity primary key,
  title text not null,
  runtime integer not null,
  pre_show integer not null default 25,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Kinovorstellungen (Spielplan)
create table if not exists shows (
  id bigint generated by default as identity primary key,
  hall integer not null,
  start_time timestamptz not null,
  movie_id bigint not null references movies(id) on delete cascade,
  version text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Mitarbeitende
create table if not exists dienstplan_employees (
  id bigint generated by default as identity primary key,
  name text not null,
  position text,
  monthly_hours numeric(6,2) not null default 0,
  user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Pausenregeln
create table if not exists dienstplan_pause_rules (
  id bigint generated by default as identity primary key,
  min_minutes integer not null,
  pause_minutes integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Schichten
create table if not exists dienstplan_shifts (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references dienstplan_employees(id) on delete cascade,
  shift_date date not null,
  start_time time,
  end_time time,
  raw_input text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, shift_date)
);

-- Dienstplaner: Schienen (Zeitslots)
create table if not exists dienstplan_shift_tracks (
  track_key text primary key,
  label text not null,
  start_time time not null,
  end_time time not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Dienstplaner: Positionsbezogener Tagesbedarf
create table if not exists dienstplan_position_requirements (
  requirement_date date not null,
  position text not null,
  track_key text references dienstplan_shift_tracks(track_key) on delete set null,
  start_time time not null,
  end_time time not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (requirement_date, position, start_time, end_time)
);

-- Dienstplaner: Verfügbarkeiten
create table if not exists dienstplan_availability (
  employee_id bigint not null references dienstplan_employees(id) on delete cascade,
  availability_date date not null,
  status text default null,
  fixed_start time,
  fixed_end time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (employee_id, availability_date)
);

-- Dienstplaner: Anforderungen pro Wochentag
create table if not exists dienstplan_weekday_requirements (
  weekday smallint not null,
  required_shifts integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (weekday)
);

-- Dienstplaner: Anforderungen pro Datum
create table if not exists dienstplan_date_requirements (
  requirement_date date not null,
  required_shifts integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (requirement_date)
);

-- Dienstplaner: Positionsbedarf pro Wochentag (Grundregeln)
create table if not exists dienstplan_weekday_position_requirements (
  id bigint generated by default as identity primary key,
  weekday smallint not null,
  track_key text not null references dienstplan_shift_tracks(track_key) on delete cascade,
  position text not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into dienstplan_shift_tracks (track_key, label, start_time, end_time)
values
  ('martinee', 'Martinée', '12:00', '16:00'),
  ('n1', 'N1', '16:00', '20:00'),
  ('n2', 'N2', '18:00', '22:00'),
  ('hv', 'HV', '19:00', '23:00'),
  ('spaet', 'Spät', '20:00', '23:59')
on conflict (track_key) do update
set label = excluded.label,
    start_time = excluded.start_time,
    end_time = excluded.end_time,
    updated_at = now();

-- Fallbacks: Primärschlüssel und Defaults ergänzen
do $$
begin
  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
     and tc.table_name = kcu.table_name
    where tc.table_schema = 'public'
      and tc.table_name = 'dienstplan_availability'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name in ('employee_id', 'availability_date')
  ) then
    alter table dienstplan_availability add primary key (employee_id, availability_date);
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dienstplan_weekday_requirements'
      and column_name = 'required_shifts'
  ) then
    alter table dienstplan_weekday_requirements add column required_shifts integer not null default 0;
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
     and tc.table_name = kcu.table_name
    where tc.table_schema = 'public'
      and tc.table_name = 'dienstplan_weekday_requirements'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name = 'weekday'
  ) then
    alter table dienstplan_weekday_requirements add primary key (weekday);
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dienstplan_date_requirements'
      and column_name = 'required_shifts'
  ) then
    alter table dienstplan_date_requirements add column required_shifts integer not null default 0;
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dienstplan_position_requirements'
      and column_name = 'track_key'
  ) then
    alter table dienstplan_position_requirements
      add column track_key text references dienstplan_shift_tracks(track_key) on delete set null;
  end if;

  if not exists (
    select 1
    from information_schema.table_constraints tc
    join information_schema.key_column_usage kcu
      on tc.constraint_name = kcu.constraint_name
     and tc.table_schema = kcu.table_schema
     and tc.table_name = kcu.table_name
    where tc.table_schema = 'public'
      and tc.table_name = 'dienstplan_date_requirements'
      and tc.constraint_type = 'PRIMARY KEY'
      and kcu.column_name = 'requirement_date'
  ) then
    alter table dienstplan_date_requirements add primary key (requirement_date);
  end if;
end $$;

-- Basisrollen anlegen/aktualisieren (User + Admin)
insert into roles (name, label, rank, is_superadmin)
values
  ('user', 'User', 0, false),
  ('admin', 'Admin', 50, false)
on conflict (name) do update
set label = excluded.label,
    rank = excluded.rank,
    is_superadmin = excluded.is_superadmin,
    updated_at = now();

-- Standardberechtigungen befüllen (0=kein Zugriff, 1=Lesen, 2=Schreiben, 3=Admin)
with seed(role_name, route, level) as (
  values
    ('user', 'dashboard', 1),
    ('user', 'tools', 1),
    ('user', 'tools/files', 2),
    ('user', 'tools/journal', 2),
    ('user', 'tools/dispoplaner', 2),
    ('user', 'tools/dienstplaner', 2),
    ('user', 'tools/dienstplaner/settings', 2),
    ('admin', 'dashboard', 1),
    ('admin', 'admin', 1),
    ('admin', 'admin/users', 1),
    ('admin', 'admin/settings', 3),
    ('admin', 'settings', 1),
    ('admin', 'monitoring', 1),
    ('admin', 'tools', 2),
    ('admin', 'tools/files', 3),
    ('admin', 'tools/journal', 3),
    ('admin', 'tools/dispoplaner', 3),
    ('admin', 'tools/dienstplaner', 3),
    ('admin', 'tools/dienstplaner/settings', 3),
    ('admin', 'tools/storage', 2),
    ('admin', 'tools/system', 2),
    ('admin', 'activity', 1)
)
insert into role_permissions (role_id, route, level)
select r.id, seed.route, seed.level
from seed
join roles r on r.name = seed.role_name
on conflict (role_id, route) do update
set level = excluded.level,
    updated_at = now();

insert into access_rules (route, role, allowed)
select seed.route, seed.role_name, (seed.level > 0) as allowed
from seed
on conflict (route, role) do update
set allowed = excluded.allowed,
    updated_at = now();

create or replace function public.get_public_tables()
returns table (table_name text)
language sql
security definer
set search_path = public
as $$
  select table_name
  from information_schema.tables
  where table_schema = 'public'
    and table_type = 'BASE TABLE'
  order by table_name;
$$;
